snowplow_media_player:
  outputs:
    dev:
      host: dataeng-staging-thrift.viki.net
      method: thrift
      port: 443
      schema: snowplow
      threads: 1
      type: spark
  target: dev

integration_tests:
  outputs:
    dev:
      host: dataeng-staging-thrift.viki.net
      method: thrift
      port: 443
      schema: snowplow
      threads: 1
      type: spark
  target: dev
