version: 2

sources:
  - name: atomic
    schema: "{{ var('snowplow__atomic_schema', 'atomic') if project_name != 'snowplow_media_player_integration_tests' else target.schema~'_snplw_media_player_int_tests' }}"
    database: "{{ var('snowplow__database', target.database) }}"
    tables:
      - name: com_snowplowanalytics_snowplow_web_page_1
        description: '{{ doc("table_page_view_context") }}'
      - name: com_snowplowanalytics_snowplow_media_player_event_1
        description: '{{ doc("table_media_player_event") }}'
      - name: com_snowplowanalytics_snowplow_media_player_1
        description: '{{ doc("table_media_player_context") }}'
      - name: com_youtube_youtube_1
        description: '{{ doc("table_youtube_context") }}'
      - name: org_whatwg_media_element_1
        description: '{{ doc("table_html_media_element_context") }}'
      - name: org_whatwg_video_element_1
        description: '{{ doc("table_html_video_element_context") }}'
