name: 'snowplow_media_player_integration_tests'
version: '0.5.1'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['data']
macro-paths: ['macros']

target-path: 'target'
clean-targets:
    - 'target'
    - 'dbt_modules'
    - 'dbt_packages'

quoting:
  identifier: false
  schema: false

models:
  snowplow_media_player_integration_tests:
    bind: false
    +schema: 'snplw_media_player_int_tests'
    source:
      bigquery:
        +enabled: '{{ target.type == "bigquery" | as_bool() }}'
      databricks:
        +enabled: '{{ target.type in ["databricks", "spark"] | as_bool() }}'
      default:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
      snowflake:
        +enabled: '{{ target.type == "snowflake" | as_bool() }}'

vars:
  snowplow_media_player:
    # Variables - Warehouse and tracker
    snowplow__percent_progress_boundaries: [10, 25, 50, 75]
    snowplow__events: '{{ ref("snowplow_media_player_events_stg") }}'
    snowplow__start_date: '2022-01-17'
    snowplow__atomic_schema: '{{ target.schema }}_snplw_media_player_int_tests'

    # Variables - Operation and logic
    snowplow__backfill_limit_days: 30

    # Variables - Contexts, filters, and logs
    snowplow__enable_youtube: true
    snowplow__enable_whatwg_media: true
    snowplow__enable_whatwg_video: true
    snowplow__enable_media_player_v1: true
    snowplow__enable_media_player_v2: true
    snowplow__enable_media_session: true
    snowplow__enable_media_ad: true
    snowplow__enable_media_ad_break: true

    # Variables - Warehouse Specific
    snowplow__page_view_context: 'snowplow_web_page_view_context'

seeds:
  quote_columns: false
  snowplow_media_player_integration_tests:
    +schema: 'snplw_media_player_int_tests'
    source:
      snowplow_media_player_events:
        +column_types:
          app_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          etl_tstamp: timestamp
          collector_tstamp: timestamp
          dvce_created_tstamp: timestamp
          user_fingerprint: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          user_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ip_isp: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ip_organization: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ip_domain: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ip_netspeed: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          page_urlfragment: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          refr_urlfragment: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          refr_medium: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          refr_source: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          refr_term: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          mkt_term: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          mkt_content: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          se_label: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          se_property: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          se_value: float
          tr_orderid: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          tr_affiliation: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          tr_total: float
          tr_tax: float
          tr_shipping: float
          tr_city: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          tr_state: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          tr_country: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ti_orderid: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ti_sku: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ti_name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ti_category: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ti_price: float
          br_name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          br_family: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          br_version: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          br_type: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          br_renderengine: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          br_colordepth: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          os_name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          os_family: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          os_manufacturer: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          dvce_type: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          dvce_ismobile: boolean
          tr_currency: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          tr_total_base: float
          tr_tax_base: float
          tr_shipping_base: float
          ti_currency: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ti_price_base: float
          base_currency: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          etl_tags: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          dvce_sent_tstamp: timestamp
          refr_domain_userid: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          refr_dvce_tstamp: timestamp
          derived_tstamp: timestamp
          true_tstamp: timestamp
          load_tstamp: timestamp

      com_snowplowanalytics_snowplow_media_player_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_snowplow_media_player_2:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_snowplow_media_session_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_snowplow_media_ad_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_snowplow_media_ad_break_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_snowplow_media_ad_quartile_event_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      org_whatwg_media_element_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp
          default_playback_rate: float

      org_whatwg_video_element_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_snowplow_media_player_event_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_youtube_youtube_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_snowplow_web_page_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_mobile_screen_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

      com_snowplowanalytics_snowplow_client_session_1:
        +enabled: '{{ target.type in ["redshift", "postgres"] | as_bool() }}'
        +quote_columns: true
        +column_types:
          root_tstamp: timestamp

    expected:
      snowplow_media_player_base_expected:
        +column_types:
          play_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          page_view_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_label: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          session_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          domain_userid: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          user_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          page_referrer: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          page_url: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          source_url: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          geo_region_name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          br_name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          dvce_type: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          os_name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          os_timezone: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          platform: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          duration_secs: float
          media_type: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_player_type: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          start_tstamp: timestamp
          end_tstamp: timestamp
          avg_playback_rate: float
          play_time_secs: float
          play_time_muted_secs: float
          paused_time_secs: float
          buffering_time_secs: float
          ads_time_secs: float
          seeks: integer
          ads: integer
          ads_clicked: integer
          ads_skipped: integer
          ad_breaks: integer
          is_played: boolean
          is_valid_play: boolean
          is_complete_play: boolean
          retention_rate: float
          percent_progress_reached: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          content_watched_sec: float
          content_watched_percent: float

      snowplow_media_player_media_stats_expected:
        +column_types:
          media_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_label: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          duration_secs: float
          media_type: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_player_type: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          play_time_mins: float
          avg_play_time_mins: float
          avg_content_watched_mins: float
          first_play: timestamp
          last_play: timestamp
          plays: integer
          valid_plays: integer
          complete_plays: integer
          impressions: integer
          avg_playback_rate: float
          play_rate: float
          completion_rate_by_plays: float
          avg_percent_played: float
          avg_retention_rate: float
          last_base_tstamp: timestamp
          _10_percent_reached: integer
          _25_percent_reached: integer
          _50_percent_reached: integer
          _75_percent_reached: integer
          _100_percent_reached: integer

      snowplow_media_player_media_ad_views_expected:
        +column_types:
          media_ad_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          platform: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_label: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          domain_userid: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          user_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          play_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ad_break_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ad_break_name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ad_break_type: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ad_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          creative_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          duration_secs: float
          skippable: boolean
          pod_position: integer
          clicked: boolean
          skipped: boolean
          _25_percent_reached: boolean
          _50_percent_reached: boolean
          _75_percent_reached: boolean
          _100_percent_reached: boolean
          viewed_at: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'

      snowplow_media_player_media_ads_expected:
        +column_types:
          media_ad_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          platform: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          media_label: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          ad_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          name: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          creative_id: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          duration_secs: float
          skippable: boolean
          pod_position: integer
          views: integer
          clicked: integer
          skipped: integer
          _25_percent_reached: integer
          _50_percent_reached: integer
          _75_percent_reached: integer
          _100_percent_reached: integer
          views_unique: integer
          clicked_unique: integer
          skipped_unique: integer
          _25_percent_reached_unique: integer
          _50_percent_reached_unique: integer
          _75_percent_reached_unique: integer
          _100_percent_reached_unique: integer
          first_view: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
          last_view: '{{ "string" if target.type in ["bigquery", "databricks", "spark"] else "varchar" }}'
