version: 2

models:
  - name: mp_events
    description: This table collects all media player events as a base table
    columns:
      - name: event_id
        description: '{{ doc("col_event_id") }}'
        tests:
          - unique
          - not_null
      - name: page_view_id
        description: '{{ doc("col_page_view_id") }}'
      - name: domain_sessionid
        description: '{{ doc("col_domain_sessionid") }}'
      - name: domain_userid
        description: '{{ doc("col_domain_userid") }}'
      - name: page_referrer
        description: '{{ doc("col_page_referrer") }}'
      - name: page_url
        description: '{{ doc("col_page_url") }}'
      - name: geo_region_name
        description: '{{ doc("col_geo_region_name") }}'
      - name: br_name
        description: '{{ doc("col_br_name") }}'
      - name: dvce_type
        description: '{{ doc("col_dvce_type") }}'
      - name: os_name
        description: '{{ doc("col_os_name") }}'
      - name: os_timezone
        description: '{{ doc("col_os_timezone") }}'
      - name: derived_tstamp
        description: '{{ doc("col_derived_tstamp") }}'
      - name: collector_tstamp
        description: '{{ doc("col_collector_tstamp") }}'
  - name: interactions
    description: This table shows all media player events and calculates respective time periods
    columns:
      - name: event_id
        description: '{{ doc("col_event_id") }}'
        tests:
          - unique
          - not_null
      - name: page_view_id
        description: '{{ doc("col_page_view_id") }}'
      - name: domain_sessionid
        description: '{{ doc("col_domain_sessionid") }}'
      - name: domain_userid
        description: '{{ doc("col_domain_userid") }}'
      - name: media_id
        description: '{{ doc("col_media_id") }}'
      - name: play_id
        description: '{{ doc("col_play_id") }}'
      - name: event_type
        description: '{{ doc("col_event_type") }}'
      - name: media_type
        description: '{{ doc("col_media_type") }}'
      - name: media_player_type
        description: '{{ doc("col_media_player_type") }}'
      - name: page_referrer
        description: '{{ doc("col_page_referrer") }}'
      - name: page_url
        description: '{{ doc("col_page_url") }}'
      - name: source_url
        description: '{{ doc("col_source_url") }}'
      - name: geo_region_name
        description: '{{ doc("col_geo_region_name") }}'
      - name: br_name
        description: '{{ doc("col_br_name") }}'
      - name: dvce_type
        description: '{{ doc("col_dvce_type") }}'
      - name: os_name
        description: '{{ doc("col_os_name") }}'
      - name: os_timezone
        description: '{{ doc("col_os_timezone") }}'
      - name: duration
        description: '{{ doc("col_duration") }}'
      - name: playback_rate
        description: '{{ doc("col_playback_rate") }}'
      - name: playback_quality
        description: '{{ doc("col_playback_quality") }}'
      - name: percent_progress
        description: '{{ doc("col_percent_progress") }}'
      - name: is_muted
        description: '{{ doc("col_is_muted") }}'
      - name: start_tstamp
        description: '{{ doc("col_start_tstamp") }}'
      - name: play_time_sec
        description: '{{ doc("col_play_time_sec") }}'
      - name: play_time_sec_muted
        description: '{{ doc("col_play_time_sec_muted") }}'
  - name: plays_by_pageview
    description: This table aggregates media player interactions to a pageview level
    columns:
      - name: play_id
        description: '{{ doc("col_play_id") }}'
        tests:
          - unique
          - not_null
      - name: page_view_id
        description: '{{ doc("col_page_view_id") }}'
      - name: media_id
        description: '{{ doc("col_media_id") }}'
      - name: domain_sessionid
        description: '{{ doc("col_domain_sessionid") }}'
      - name: domain_userid
        description: '{{ doc("col_domain_userid") }}'
      - name: duration
        description: '{{ doc("col_duration") }}'
      - name: media_type
        description: '{{ doc("col_media_type") }}'
      - name: media_player_type
        description: '{{ doc("col_media_player_type") }}'
      - name: page_referrer
        description: '{{ doc("col_page_referrer") }}'
      - name: page_url
        description: '{{ doc("col_page_url") }}'
      - name: source_url
        description: '{{ doc("col_source_url") }}'
      - name: geo_region_name
        description: '{{ doc("col_geo_region_name") }}'
      - name: br_name
        description: '{{ doc("col_br_name") }}'
      - name: dvce_type
        description: '{{ doc("col_dvce_type") }}'
      - name: os_name
        description: '{{ doc("col_os_name") }}'
      - name: os_timezone
        description: '{{ doc("col_os_timezone") }}'
      - name: start_tstamp
        description: '{{ doc("col_start_tstamp") }}'
      - name: end_tstamp
        description: '{{ doc("col_end_tstamp") }}'
      - name: play_time_sec
        description: '{{ doc("col_play_time_sec") }}'
      - name: play_time_sec_muted
        description: '{{ doc("col_play_time_sec_muted") }}'
      - name: is_played
        description: '{{ doc("col_is_played") }}'
      - name: is_valid_play
        description: '{{ doc("col_is_valid_play") }}'
      - name: retention_rate
        description: '{{ doc("col_retention_rate") }}'
      - name: avg_playback_rate
        description: '{{ doc("col_avg_playback_rate") }}'
      - name: is_complete_play
        description: '{{ doc("col_is_complete_play") }}'
      - name: seeks
        description: '{{ doc("col_seeks") }}'
      - name: x_percent_passed
        description: '{{ doc("col__percent_passed") }}'

  - name: plays_by_session
    description: This table aggregates the pageview level interactions to show session level media stats
    columns:
      - name: domain_sessionid
        description: '{{ doc("col_domain_sessionid") }}'
        tests:
          - unique
          - not_null
      - name: domain_userid
        description: '{{ doc("col_domain_userid") }}'
      - name: impressions
        description: '{{ doc("col_impressions") }}'
      - name: videos_played
        description: '{{ doc("col_videos_played") }}'
      - name: audio_played
        description: '{{ doc("col_audio_played") }}'
      - name: video_plays
        description: '{{ doc("col_video_plays") }}'
      - name: audio_plays
        description: '{{ doc("col_audio_plays") }}'
      - name: valid_video_plays
        description: '{{ doc("col_valid_video_plays") }}'
      - name: valid_audio_plays
        description: '{{ doc("col_valid_audio_plays") }}'
      - name: start_tstamp
        description: '{{ doc("col_start_tstamp") }}'
      - name: end_tstamp
        description: '{{ doc("col_end_tstamp") }}'
      - name: seeks
        description: '{{ doc("col_seeks") }}'
      - name: play_time_sec
        description: '{{ doc("col_play_time_sec") }}'
      - name: play_time_sec_muted
        description: '{{ doc("col_play_time_sec_muted") }}'
      - name: avg_play_time_sec
        description: '{{ doc("col_avg_play_time_sec") }}'
      - name: avg_percentage_played
        description: '{{ doc("col_avg_percentage_played") }}'
      - name: complete_plays
        description: '{{ doc("col_complete_plays") }}'
  - name: user_stats
    description: This table aggregates the pageview level interactions to show user level media stats
    columns:
      - name: domain_userid
        description: '{{ doc("col_domain_userid") }}'
        tests:
          - unique
          - not_null
      - name: first_play
        description: '{{ doc("col_first_play") }}'
      - name: last_play
        description: '{{ doc("col_last_play") }}'
      - name: video_plays
        description: '{{ doc("col_video_plays") }}'
      - name: audio_plays
        description: '{{ doc("col_audio_plays") }}'
      - name: valid_video_plays
        description: '{{ doc("col_valid_video_plays") }}'
      - name: valid_audio_plays
        description: '{{ doc("col_valid_audio_plays") }}'
      - name: play_time_min
        description: '{{ doc("col_play_time_min") }}'
      - name: avg_play_time_min
        description: '{{ doc("col_avg_play_time_min") }}'
      - name: avg_percentage_played
        description: '{{ doc("col_avg_percentage_played") }}'
      - name: seeks
        description: '{{ doc("col_seeks") }}'
      - name: complete_plays
        description: '{{ doc("col_complete_plays") }}'
  - name: media_stats
    description: This table aggregates the pageview level interactions to show overall media stats
    columns:
      - name: media_id
        description: The primary key of this table
        tests:
          - unique
          - not_null
      - name: duration
        description: '{{ doc("col_duration") }}'
      - name: media_type
        description: '{{ doc("col_media_type") }}'
      - name: media_player_type
        description: '{{ doc("col_media_player_type") }}'
      - name: play_time_h
        description: '{{ doc("col_play_time_h") }}'
      - name: avg_play_time_min
        description: '{{ doc("col_avg_play_time_min") }}'
      - name: first_play
        description: '{{ doc("col_first_play") }}'
      - name: last_play
        description: '{{ doc("col_last_play") }}'
      - name: plays
        description: '{{ doc("col_plays") }}'
      - name: valid_plays
        description: '{{ doc("col_valid_plays") }}'
      - name: complete_plays
        description: '{{ doc("col_complete_plays") }}'
      - name: users
        description: '{{ doc("col_users") }}'
      - name: users_w_complete_plays
        description: '{{ doc("col_users_w_complete_plays") }}'
      - name: returning_users
        description: '{{ doc("col_returning_users") }}'
      - name: impressions
        description: '{{ doc("col_impressions") }}'
      - name: avg_playback_rate
        description: '{{ doc("col_avg_playback_rate") }}'
      - name: play_rate
        description: '{{ doc("col_play_rate") }}'
      - name: completion_rate_by_plays
        description: '{{ doc("col_completion_rate_by_plays") }}'
      - name: completion_rate_by_user
        description: '{{ doc("col_completion_rate_by_user") }}'
      - name: avg_percentage_played
        description: '{{ doc("col_avg_percentage_played") }}'
      - name: avg_retention_rate
        description: '{{ doc("col_avg_retention_rate") }}'
      - name: x_percent_passed
        description: '{{ doc("col__percent_passed") }}'
  - name: pivot_base
    description: This table serves as a base to add percent_progress_passed fields to tables
    columns:
      - name: percent_progress
        description: '{{ doc("col_percent_progress") }}'
        tests:
          - unique
          - not_null
      - name: weight_rate
        description: '{{ doc("col_weight_rate") }}'
