version: 2

sources:
  - name: atomic
    schema: atomic
    database: snplow5
    tables:
      - name: events
      - name: com_snowplowanalytics_snowplow_web_page_1
      - name: com_snowplowanalytics_snowplow_media_player_event_1
      - name: com_snowplowanalytics_snowplow_media_player_1
      - name: com_youtube_youtube_1
      - name: org_whatwg_media_element_1
      - name: org_whatwg_video_element_1
